project_id = "gvpblngewoicxdwcirts"

[functions.sync-wallet-transactions]
verify_jwt = false

[functions.claim-merchant]
verify_jwt = false

[functions.save-pending-wallet]
verify_jwt = false

[functions.test-wallet-connection]
verify_jwt = false
